### ISSUE TITLE
Support multiple closed tracks

### ISSUE THREAD

**Issue by pwatt01** [drstranges/BambooGooglePlayPublisher#2]
We have multiple internal test tracks for our apps and was wondering if this can support that, or is it stuck with the Internal/Aplha/ etc?

**Comment by drstranges** [comment]
What do you mean "multiple internal test tracks"? Don't Google Play provide only one internal testers track?

**Comment by pwatt01** [comment]
Hi There,

Sorry i worded the question poorly. You are correct there is only 1 internal test track, but you can have 1...n Closed tracks by default the first is called Alpha.

**Comment by drstranges** [comment]
Ok, I get it. Thank you.
Added to todo-list. In a few days I'll try to implement this if Publish SDK supports custom tracks.

**Comment by drstranges** [comment]
fixed in v2.0.0
